[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/xmlrpc"
  to = "/.netlify/functions/xmlrpc"
  status = 200

[[redirects]]
  from = "/xmlrpc.php"
  to = "/.netlify/functions/xmlrpc"
  status = 200

[[redirects]]
  from = "/micropub"
  to = "/.netlify/functions/micropub"
  status = 200

[[redirects]]
  from = "/micropub-media"
  to = "/.netlify/functions/micropub-media"
  status = 200
